server:
  # 服务端口
  port: 8081
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
  #database
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.10.43.57:3306/luckydb?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 1234
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1
mybatis:
  type-aliases-package: com.wm.gameplat.controller.usercenter.domain
  mapper-locations: classpath:mapper/*Mapper.xml
captcha:
  image:
  - /usercenter/login

token:
  # 设置为true后，token将存入redis，并具有单点登录功能 默认false使用JWT交互
  redis: true
  # 是否开启单设备登陆 仅当token交互方式为redis时生效
  sdl: true
  # token中存储用户权限数据 设为true开启后可避免每次请求再获取用户权限，但有可能导致编辑权限菜单后无法读取到最新权限数据（需用户重新登录）
  storePerms: true
  # token过期时间（分钟）
  tokenExpireTime: 60
  # 用户选择保存登录状态对应token过期时间（天）
  saveLoginTime: 7
  # 限制用户登陆错误次数（次）
  loginTimeLimit: 10
  # 错误超过次数后多少分钟后才能继续登录（分钟）
  loginAfterTime: 10
  # 日志记录方式 true使用Elasticsearch记录 false记录至数据库中